# ################ #
#  BetterSleeping  #
# ################ #

# To reset this file, you can simply delete it.
# Useful links:
# Our Spigot plugin page:                                       https://www.spigotmc.org/resources/bettersleeping-1-12-1-14.60837/
# For support or suggestions, head over to our Discord server:  https://discord.gg/AS46VGT
# You can find a live list of upcoming features/bug fixes here: https://github.com/Nuytemans-Dieter/BetterSleeping/issues
# The progress of the next release can be found here:           https://github.com/Nuytemans-Dieter/BetterSleeping/milestones


# --------------- #
# Sleep settings  |
# --------------- #


# Set the percentage of online players that need to be sleeping 
# in order to skip the night/storm. Will be rounded up!
# Example: 2 online players + this is set to 51 => 51% * 2 = 1,02 but it will be rounded up so: 2 players needed!
# Default: 30
percentage_needed: 30


# Set the time (in ticks) that players will have to remain in their beds when enough people are sleeping
# A delay of one second is equal to 20 ticks so setting this to 40 means a delay of two seconds which roughly equals the single player delay
# Default: 40
sleep_delay: 40


# Set the time (in seconds) that players have to wait before they can enter a bed again after getting out of bed
# Default: 10
bed_enter_delay: 10


# Choose whether or not AFK players (Essentials is required) will be counted towards the amount of sleeping players needed
# Default: true
essentials_afk_support: true


# Choose whether BetterSleeping should treat every world seperate from eachother (when set to true)
#       percentage_needed:  30 would mean that 30% of all players IN WORLD X should be sleeping
#                           If this condition is met, the night/storm will ONLY be skipped in that same world
#           Example:        There are 100 online players, 90 in world1 and 10 in world2.
#                           3 people are sleeping in the world2 and since 30% of people in that world are sleeping
#                           The night will be skipped, but ONLY in world2
# Or if it should count the global number of sleeping players and skip the night/storm in all worlds (when set to false)
#       percentage_needed:  30 would mean that 30% of all ONLINE players should be sleeping
#                           If this condition is met, the night/storm will be skipped in EVERY world
#           Example:        There are 100 online players, 90 in world1 and 10 in world2.
#                           30 people (of all worlds combined) must be sleeping in order to skip the night/storm.
#                           The night/storm will be skipped in EVERY world!!
# Default: true
multiworld_support: true


# --------------- #
# Bypass settings |
# --------------- #


# Decide whether or not players with sleeping bypass permissions get buffs (bettersleeping.bypass OR essentials.sleepingignored)
# Those players can never sleep, even if they want to
# Default: true
buffs_for_bypassing_players: true


# Here you can choose whether or not you want BetterSleeping to ignore players with each gamemode
# Default: false
ignore_survival: false
# Default: false
ignore_creative: false
# Default: false
ignore_adventure: false
# Default: false
ignore_spectator: false


# Choose whether or not phantoms are disabled
# Setting this to true means that phantoms will never spawn again (counts for ALL phantoms)
# Phantoms that spawned before setting this to true will still live until despawned or killed
# Please do not set this to true if you are using a Spigot version below 1.13 as this will cause errors in the console
# Defaut: false
disable_phantoms: false


# ----------------- #
# Messages settings |
# ----------------- #

# Choose where the messages will appear
# Setting this to true will result in the messages being sent to the chat
# Setting this to false will result in the messages being shown on screen
# !IMPORTANT!
# ONLY if set to false
# Sometimes several messages are sent at once. Only the last message will be shown on screen!
# Please disable the messages below in lang.yml or people may never receive 'good_morning'
#   - buff_received: "ignored"
#   - no_buff_received: "ignored"
# If you really want to say good morning AND list the amount of buffs received:
#   - Disable 'good_morning' and add your good morning to the two messages listed above.
# Default: true
messages_in_chat: true