#  ____       _   _            _____ _                 _              
# |  _ \     | | | |          / ____| |               (_)             
# | |_) | ___| |_| |_ ___ _ _| (___ | | ___  ___ _ __  _ _ __   __ _  
# |  _ < / _ \ __| __/ _ \ '__\___ \| |/ _ \/ _ \ '_ \| | '_ \ / _` | 
# | |_) |  __/ |_| ||  __/ |  ____) | |  __/  __/ |_) | | | | | (_| | 
# |____/ \___|\__|\__\___|_| |_____/|_|\___|\___| .__/|_|_| |_|\__, | 
#                                               | |             __/ | 
#                                               |_|            |___/  


# To reset this file, you can simply delete it.
# Useful links:
# Our Spigot plugin page:                                       https://www.spigotmc.org/resources/bettersleeping-1-12-1-14.60837/
# For support or suggestions, head over to our Discord server:  https://discord.gg/AS46VGT
# You can find a live list of upcoming features/bug fixes here: https://github.com/Nuytemans-Dieter/BetterSleeping/issues
# The progress of the next release can be found here:           https://github.com/Nuytemans-Dieter/BetterSleeping/milestones


# Choose whether or not BetterSleeping should check for updates on startup
# No information from your server is shared or collected in this process.
# Default: true
update_checker: true


# --------------- #
# Sleep settings  |
# --------------- #


# Set the percentage of online players that need to be sleeping to skip the night/storm
# The number of players will be rounded up!
# Example: 2 online players + this is set to 51 => 51% * 2 = 1,02 but it will be rounded up so: 2 players needed!
# Default: 30
percentage_needed: 30


# Set the time (in ticks) that players will have to remain in their beds when enough people are sleeping
# A delay of one second is equal to 20 ticks so setting this to 40 means a delay of two seconds which roughly equals the single player delay
# Default: 40
sleep_delay: 40


# Set the time (in seconds) that players have to wait before they can enter a bed again after getting out of bed
# This prevents a player's ability to spam the other players
# Default: 10
bed_enter_delay: 10


# Choose whether or not AFK players (Essentials is required) will be counted towards the amount of sleeping players needed
# AFK time is not taken into account. Players may abuse this by setting themselves afk to lower the amount of required sleeping players
# Default: true
essentials_afk_support: true


# --------------- #
# Bypass settings |
# --------------- #


# !!!PLEASE READ BEFORE EDITING!!!
# Due to popular demand, bypass permissions can now be disabled. There is a catch, however.
# An issue may arise when this is set to false and Essentials is installed:
# When everyone (except for OPs) is sleeping, the night is skipped instantly and BetterSleeping will send a message saying that skipping the night was canceled!
# If set to true, BetterSleeping will ignore those players and this bug can no longer occur.
# If you want to prevent this bug AND allow OPs to sleep, please do the following:
# Add both permissions (below) to all OPs, using a permissions plugin like PermissionsEx, LuckPerms, GroupManager, etc.
# Negate bettersleeping.bypass AND essentials.sleepingignored
#   With permissionsEx, negating is done by adding a '-' in front of the permission
#   With LuckPerms, negating is done by setting the permission node to false
# Gamemodes can still be ignored if this is set to false.
# Now that you know all the details, you can safely make the right decision.
# Default: true
enable_bypass_permissions: true


# Decide whether or not players with sleeping bypass permissions will get buffs
# Those players cannot sleep, even if they want to
# Default: true
buffs_for_bypassing_players: true


# Choose whether or not vanished players should be ignored
# The plugins on the line below are supported
# Essentials, Essentials-compatible vanish plugins, PremiumVanish, SuperVanish, VanishNoPacket and more!
# Without a supported plugin, this setting will have no effect
# Default: true
ignore_vanished_players: true


# Here you can choose whether or not you want BetterSleeping to ignore players with each gamemode
# Default: false
ignore_survival: false
# Default: false
ignore_creative: false
# Default: false
ignore_adventure: false
# Default: false
ignore_spectator: false


# Choose whether or not phantoms are disabled
# Setting this to true means that phantoms will never spawn again (counts for ALL phantoms)
# Phantoms that spawned before setting this to true will still live until despawned or killed
# Please do not set this to true if you are using a Spigot version below 1.13 as this can cause errors in the console
# Default: false
disable_phantoms: false


# ----------------- #
# Messages settings |
# ----------------- #


# Choose whether or not everyone in the same world should receive all messages
# When an option is set to false, that message will only be sent to players that are sleeping.
# Default: true
enough_sleeping_public: true
# Default: true
good_morning_public: true
# Default: true
cancelled_public: true
# Default: true
amount_left_public: true


# Choose whether or not a sound will be played when a player receives a BetterSleeping message
# Default: false
message_sound: false


# Choose where the messages will appear
# Setting this to true will result in the messages being sent to the chat
# Setting this to false will result in the messages being shown on screen
# !IMPORTANT!
# ONLY if set to false
# Sometimes several messages are sent at once. Only the last message will be shown on screen!
# Please disable the messages below in lang.yml or people may never receive 'good_morning'
#   - buff_received: "ignored"
#   - no_buff_received: "ignored"
# If you really want to say good morning AND list the amount of buffs received:
#   - Disable 'good_morning' and add your good morning to the two messages listed above.
# A faulty configuration will be reported to console upon startup or reload
# Default: true
messages_in_chat: true
