name: betterSleeping
author: vallas
version: 2.2.0
main: be.dezijwegel.bettersleeping.BetterSleeping
description: A plugin that makes sleeping in multiplayer fun again!
commands:
    bettersleeping:
        description: See all BetterSleeping commands
        usage: /bettersleeping reload or /bs reload
        permission: bettersleeping.reload
        aliases: [bs]