name: BetterSleeping
author: vallas
version: 2.4.0
main: be.dezijwegel.BetterSleeping
description: A plugin that makes sleeping in multiplayer fun again!
softdepend: [Essentials, PlaceholderAPI]
commands:
    bettersleeping:
        description: See all BetterSleeping commands
        usage: /bettersleeping reload or /bs reload
        permission: bettersleeping.reload
        aliases: [bs]